# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       nemo-qml-plugin-systemsettings

# >> macros
# << macros

Summary:    System settings plugin for Nemo Mobile
Version:    0.0.0
Release:    1
Group:      System/Libraries
License:    BSD
URL:        https://github.com/nemomobile/nemo-qml-plugin-systemsettings
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-qml-plugin-systemsettings.yaml
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(qmsystem2)
BuildRequires:  pkgconfig(profile)
BuildRequires:  pkgconfig(QtSystemInfo)

%description
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/systemsettings/libnemosystemsettings.so
%{_libdir}/qt4/imports/org/nemomobile/systemsettings/qmldir
# >> files
# << files
